#How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

x = set()
def find_powers():
    for a in range(2, 101):
        for b in range(2, 101):
            x.add(a**b)
    return len(x)

print(find_powers())
