import math
#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


pentagon = [1]
test = []
def find_pentagon():
    n=2
    while True:
        p = int(n*(3*n-1)/2)
        pentagon.append(p)
        test.extend([[p, pentagon[i]] for i in range(len(pentagon)-1) if (p-pentagon[i]) in pentagon and (1+math.sqrt(1+24*(p+pentagon[i])))%6==0])
        if len(test)>0: break
        n+=1
    return abs(test[0][1]-test[0][0])

print(find_pentagon())
